targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - test/cmis_browser_test.dart
      #build_vm_compilers|entrypoint:
        #generate_for:
          #- test/multiplatform/**_test.dart
